#!/bin/sh
set -xe

# Type any extra commands inside this function. They will run last.
extra_commands() {
  apk --no-cache add byobu musl-locales neovim bash bash-completion
  su - root -c byobu-enable
  ln -sf "$(command -v nvim)" /usr/bin/vim
}

create_executable() {
  filename="$1"
  create_file "${filename}"
  chmod +x "${filename}"
}

create_file() {
  filename="$1"
  mkdir -p "$(dirname "${filename}")"
  cat >"${filename}"
}

create_file_if_not_exists() {
  filename="$1"
  if [ ! -e "${filename}" ]; then
    create_file "${filename}"
  else
    cat >/dev/null
  fi
}

enable_service() {
  name="$1"
  rc-update add "${name}" boot
}

create_service() {
  name="$1"
  create_executable "/etc/init.d/${name}"
  enable_service "${name}"
}

create_executable "/etc/local.d/update-issue.start" <<'EOF'
#!/bin/sh
set -e
hr() {
  echo "----------------------------------------------------------------------"
}
sed "/-----/,100d" -i /etc/issue || true
sed "/Link encap/,100d" -i /etc/issue || true
hr >> /etc/issue
/sbin/ifconfig | grep -vE '^lo ' | grep -EA2 '^[^ ]' >> /etc/issue
hr >> /etc/issue
EOF

apk upgrade --no-cache
apk add --no-cache curl podman podman-bash-completion podman-docker podman-tui podman-openrc openssh-server pipx
pipx install podman-compose

enable_service local
enable_service sshd
enable_service podman

appdata_dir="/appdata"
podman_compose_file="${appdata_dir}/podman-compose.yml"
create_service podman-compose <<EOF
#!/sbin/openrc-run

################################################################################
# Manages a podman-compose service.
################################################################################

appdata_dir="${appdata_dir}"
podman_compose_file="${podman_compose_file}"

name=\$RC_SVCNAME
description="Docker Compose Application Service"
description_reload="Reload changes in \${podman_compose_file}"

depend() {
	after podman
	need podman
}

extra_started_commands="reload"

_podman_compose() {
  podman-compose --file "\${podman_compose_file}" "\$@"
}

_podman_compose_up() {
  _podman_compose up --detach --remove-orphans --pull=always --wait
}

checkconfig() {
  _podman_compose config --quiet
}

start_pre() {
  # If this isn't a restart, make sure that the user's config isn't
  # busted before we try to start the daemon (this will produce
  # better error messages than if we just try to start it blindly).
  #
  # If, on the other hand, this *is* a restart, then the stop_pre
  # action will have ensured that the config is usable and we don't
  # need to do that again.
  if [ "\${RC_CMD}" != "restart" ] ; then
    checkconfig || return \$?
  fi

  if ! podman info 2>/dev/null >/dev/null; then
    ebegin "Waiting for Docker daemon to be ready..."
    timeout 15 sh -c 'until podman info 2>/dev/null >/dev/null; do sleep 1; done;'
    if [ \$? -eq 0 ]; then
      eend 0 "Docker daemon is ready"
    else
      eend 1 "Docker daemon is not ready"
    fi
  fi
}

stop_pre() {
  # If this is a restart, check to make sure the user's config
  # isn't busted before we stop the running daemon.
  if [ "\${RC_CMD}" = "restart" ] ; then
      checkconfig || return \$?
  fi
}

start() {
	ebegin "Starting \$RC_SVCNAME"
  _podman_compose_up
	eend \$?
}

reload() {
  ebegin "Reloading \$RC_SVCNAME's \${podman_compose_file}"
  _podman_compose_up
  eend \$?
}

stop() {
	ebegin "Stopping \$RC_SVCNAME"
	if ! [ -r "\${podman_compose_file}" ]; then
    service podman stop &
    eend 0
    return 0
  fi
	_podman_compose down
	eend \$?
}
EOF

create_service podman-compose-watchdog <<EOF
#!/sbin/openrc-run

################################################################################
# Keeps an instance of podman-compose-watchdog running.
################################################################################

supervisor="supervise-daemon"
command="/usr/bin/podman-compose-watchdog"
stopsig="HUP"
retry="INT/5/TERM/5/KILL/5"
EOF

create_executable "/usr/bin/podman-compose-watchdog" <<EOF
#!/bin/sh
set -e

################################################################################
# Watches the ${podman_compose_file} file for changes and reloads the
# podman-compose service when it does.
#
# This script is intended to be run by the podman-compose-watchdog service.
################################################################################

podman_compose_file="${podman_compose_file}"
inotifyd_max_wait="60"
previous_hash=""
current_hash=""
inotifyd_pid=""
shutting_down=""

handle_signal() {
  shutting_down="true"
  if [ -n "\${inotifyd_pid}" ]; then
    echo "Received signal, terminating inotifyd" >&2
    kill "\${inotifyd_pid}"
    wait "\${inotifyd_pid}" || true
  fi
  exit 0
}
trap handle_signal HUP INT TERM QUIT ABRT KILL

get_hash() {
  if ! [ -r "\${podman_compose_file}" ]; then
    echo "N/A"
  else
    sha256sum "\${podman_compose_file}" | cut -d' ' -f1
  fi
}

is_still_the_same_hash() {
  current_hash="\$(get_hash)"
  if [ "\${current_hash}" = "\${previous_hash}" ]; then
    previous_hash="\${current_hash}"
    return 0
  else
    previous_hash="\${current_hash}"
    return 1
  fi
}

has_the_file_changed() {
  ! is_still_the_same_hash
}

main() {
  while true; do
    if has_the_file_changed; then
      podman-compose-reload
      sleep 1
      continue
    fi

    if [ -r "\${podman_compose_file}" ]; then
      timeout "\${inotifyd_max_wait}" inotifyd : "\${podman_compose_file}":cew0uoDMx &
      inotifyd_pid="\$!"
      echo "Waiting up to \${inotifyd_max_wait} seconds for changes to \${podman_compose_file} in inotifyd pid \${inotifyd_pid}" >&2
      wait "\${inotifyd_pid}"
      echo "inotifyd terminated" >&2
      if [ -n "\${shutting_down}" ]; then
        echo "Breaking watch loop because we're shutting down" >&2
        break
      fi
      echo "Clearing inotifyd pid" >&2
      inotifyd_pid=""
    else
      sleep 1
    fi
  done
  echo "Exited main loop" >&2
}

main "\$@"
EOF

create_executable "/usr/bin/podman-compose-reload" <<EOF
#!/bin/sh
set -e

################################################################################
# Makes sure that the podman-compose service is running and up-to-date with any
# ${podman_compose_file} file.
#
# Takes down the service if the file is not readable. If the file is not ok, it
# does nothing.
#
# This script is intended to be run by the podman-compose-watchdog service.
################################################################################

podman_compose_file="${podman_compose_file}"

is_podman_compose_running() {
  service podman-compose status --quiet
}

is_podman_compose_file_readable() {
  test -r "\${podman_compose_file}"
}

is_podman_compose_file_ok() {
  podman-compose -f "\${podman_compose_file}" config --quiet
}

main() {
  if ! is_podman_compose_file_readable; then
    service podman-compose stop
    return 0
  fi

  if ! is_podman_compose_file_ok; then
    return 0
  fi

  if ! is_podman_compose_running; then
    service podman-compose start
    return 0
  fi

  service podman-compose reload
}

main "\$@"
EOF

create_file_if_not_exists "${podman_compose_file}" <<EOF
services:
  # https://containrrr.dev/watchtower/arguments/
  watchtower:
    image: podman.io/containrrr/watchtower
    environment:
      - WATCHTOWER_CLEANUP=true
    volumes:
      - /var/run/podman.sock:/var/run/podman.sock

  # your app here
  app:
    image: podman.io/traefik/whoami
    environment:
      - PORT=80
    ports: [ "80:80" ]
#   volumes:
#     - ${appdata_dir}/data:/data:ro    # left side is inside lxc, right is inside podman
EOF

extra_commands
