#!/bin/sh
set -xe

# Type any extra commands inside this function. They will run last.
extra_commands() {
  apt-get install -y byobu neovim bash bash-completion
  update-alternatives --set vim "$(command -v nvim)"
  su - root -c byobu-enable
}

create_executable() {
  filename="$1"
  create_file "${filename}"
  chmod +x "${filename}"
}

create_file() {
  filename="$1"
  mkdir -p "$(dirname "${filename}")"
  cat >"${filename}"
}

create_file_if_not_exists() {
  filename="$1"
  if [ ! -e "${filename}" ]; then
    create_file "${filename}"
  else
    cat >/dev/null
  fi
}

enable_service() {
  name="$1"
  systemctl enable "${name}"
}

create_service() {
  name="$1"
  create_file "/etc/systemd/system/${name}.service"
  systemctl daemon-reload
  enable_service "${name}"
}

create_executable "/etc/update-motd.d/80-network" <<'EOF'
#!/bin/sh
set -e
echo "----------------------------------------------------------------------"
ip a | grep -E '(^[^ ]|\binet6? [^ ]+)'
echo "----------------------------------------------------------------------"
EOF

apt-get update
apt-get full-upgrade -y --purge --autoremove
apt-get install -y curl openssh-server inotify-tools unattended-upgrades podman podman-docker docker-compose

create_executable "/usr/bin/docker-compose-service-wait-for-docker-engine" <<EOF
#!/usr/bin/env bash
set -euo pipefail
IFS=\$'\n\t'

################################################################################
# Waits for the container engine to be ready.
################################################################################

if /usr/bin/docker info 2>/dev/null >/dev/null; then
  echo "Container engine is ready"
  exit 0
fi

echo "Waiting for Docker daemon to be ready..."

/usr/bin/timeout 15 sh -c "until /usr/bin/docker info 2>/dev/null >/dev/null; do sleep 1; done;"
if [[ \$? -eq 0 ]]; then
  echo "Container engine is now ready"
  exit 0
fi

echo "Container engine is still not ready"
exit 1
EOF

create_executable "/usr/bin/docker-compose-service-stop" <<EOF
#!/usr/bin/env bash
set -euo pipefail
IFS=\$'\n\t'

################################################################################
# Used by the docker-compose service to stop the docker compose stack.
# If the docker compose file is not readable, it will remove all containers.
################################################################################

if [[ ! -r "\${docker_compose_file}" ]]; then
  /usr/bin/podman rm --all --force
  exit 0
fi

/usr/bin/docker-compose --file "\${docker_compose_file}" down
EOF

appdata_dir="/appdata"
docker_compose_file="${appdata_dir}/docker-compose.yml"
create_service docker-compose <<EOF
[Unit]
Description=Docker Compose Application Service
After=podman.socket
Requires=podman.socket

[Service]
Environment=docker_compose_file=${docker_compose_file}
ExecStartPre=/usr/bin/docker-compose-service-wait-for-docker-engine
ExecStartPre=/usr/bin/docker-compose --file "\${docker_compose_file}" config --quiet
ExecReload=/usr/bin/docker-compose   --file "\${docker_compose_file}" config --quiet
ExecStart=/usr/bin/docker-compose    --file "\${docker_compose_file}" up --remove-orphans
ExecReload=/usr/bin/docker-compose   --file "\${docker_compose_file}" up --remove-orphans --detach
ExecStop=/usr/bin/docker-compose-service-stop
Restart=always

[Install]
WantedBy=multi-user.target
EOF

create_service docker-compose-watchdog <<EOF
[Unit]
Description=Keeps an instance of docker-compose-watchdog running

[Service]
ExecStart=/usr/bin/docker-compose-watchdog
Restart=always
KillSignal=SIGHUP
KillMode=mixed
TimeoutStopSec=5

[Install]
WantedBy=multi-user.target
EOF

create_executable "/usr/bin/docker-compose-watchdog" <<EOF
#!/bin/sh
set -e

################################################################################
# Watches the ${docker_compose_file} file for changes and reloads the
# docker-compose service when it does.
#
# This script is intended to be run by the docker-compose-watchdog service.
################################################################################

docker_compose_file="${docker_compose_file}"
inotifywait_max_wait="60"
previous_hash=""
current_hash=""
inotifywait_pid=""
shutting_down=""

handle_signal() {
  shutting_down="true"
  if [ -n "\${inotifywait_pid}" ]; then
    echo "Received signal, terminating inotifywait" >&2
    kill "\${inotifywait_pid}"
    wait "\${inotifywait_pid}" || true
  fi
  exit 0
}
trap handle_signal HUP INT TERM QUIT ABRT KILL

get_hash() {
  if ! [ -r "\${docker_compose_file}" ]; then
    echo "N/A"
  else
    sha256sum "\${docker_compose_file}" | cut -d' ' -f1
  fi
}

is_still_the_same_hash() {
  current_hash="\$(get_hash)"
  if [ "\${current_hash}" = "\${previous_hash}" ]; then
    previous_hash="\${current_hash}"
    return 0
  else
    previous_hash="\${current_hash}"
    return 1
  fi
}

has_the_file_changed() {
  ! is_still_the_same_hash
}

main() {
  while true; do
    if has_the_file_changed; then
      docker-compose-reload
      sleep 1
      continue
    fi

    if [ -r "\${docker_compose_file}" ]; then
      inotifywait --timeout "\${inotifywait_max_wait}" --event modify --event attrib --event move_self --event delete_self --event unmount "\${docker_compose_file}" &
      inotifywait_pid="\$!"
      echo "Waiting up to \${inotifywait_max_wait} seconds for changes to \${docker_compose_file} in inotifywait pid \${inotifywait_pid}" >&2
      wait "\${inotifywait_pid}"
      echo "inotifywait terminated" >&2
      if [ -n "\${shutting_down}" ]; then
        echo "Breaking wait loop because we're shutting down" >&2
        break
      fi
      echo "Clearing inotifywait pid" >&2
      inotifywait_pid=""
    else
      sleep 1
    fi
  done
  echo "Exited main loop" >&2
}

main "\$@"
EOF

create_executable "/usr/bin/docker-compose-reload" <<EOF
#!/bin/sh
set -e

################################################################################
# Makes sure that the docker-compose service is running and up-to-date with any
# ${docker_compose_file} file.
#
# Takes down the service if the file is not readable. If the file is not ok, it
# does nothing.
#
# This script is intended to be run by the docker-compose-watchdog service.
################################################################################

docker_compose_file="${docker_compose_file}"

is_docker_compose_running() {
  systemctl is-active docker-compose --quiet
}

is_docker_compose_file_readable() {
  test -r "\${docker_compose_file}"
}

is_docker_compose_file_ok() {
  docker-compose -f "\${docker_compose_file}" config --quiet
}

main() {
  if ! is_docker_compose_file_readable; then
    service docker-compose stop
    return 0
  fi

  if ! is_docker_compose_file_ok; then
    return 0
  fi

  if ! is_docker_compose_running; then
    service docker-compose start
    return 0
  fi

  service docker-compose reload
}

main "\$@"
EOF

create_file_if_not_exists "${docker_compose_file}" <<EOF
services:
  app:
    image: docker.io/traefik/whoami
    environment:
      - PORT=80
    ports: [ "80:80" ]
    labels:
      - io.containers.autoupdate=registry
#   volumes:
#     - ${appdata_dir}/data:/data:ro    # left side is inside lxc, right is inside container
EOF

extra_commands
